language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mysql

env:
  global:
    - MYSQL_HOST=127.0.0.1
    - MYSQL_PORT=3306
    - MYSQL_USER=root
    - MYSQL_PASSWORD=""
    - MYSQL_DATABASE=test

before_install:
  - mysql -e 'select version()'
  - mysql -e 'CREATE DATABASE test'

install:
  - composer install
  - composer require phpunit/phpunit --dev

script:
  - vendor/bin/phpunit --version
  - vendor/bin/phpunit --colors --coverage-text

before_deploy:
  - composer build

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: dbdatool.phar
  skip_cleanup: true
  on:
    php: 7.2
    tags: true
