CREATE TABLE t1 (
  id INT NOT NULL PRIMARY KEY,
  str TEXT
);

CREATE TABLE t2 (
  id INT NOT NULL PRIMARY KEY,
  str TEXT
);

ALTER TABLE t2 ADD CONSTRAINT fk FOREIGN KEY (id) REFERENCES t1 (id) ON UPDATE NO ACTION ON DELETE NO ACTION;
