DROP TABLE IF EXISTS t1;
DROP TABLE IF EXISTS t2;
DROP TABLE IF EXISTS t3;

CREATE TABLE t1
(
  CHECK (c1 <> c2),
  c1 INT CHECK (c1 > 10),
  c2 INT CONSTRAINT c2x_positive CHECK (c2 > 0),
  c3 INT CHECK (c3 < 200),
  CONSTRAINT c1_nonzero CHECK (c1 <> 0) NOT ENFORCED,
  CHECK (c1 > c3) NOT ENFORCED
);

CREATE TABLE t3
(
  CHECK (c1 <> c2),
  c1 INT CHECK (c1 > 10),
  c2 INT
);
