
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

ALTER TABLE `t`
  DROP PRIMARY KEY,
  DROP COLUMN `id`,
  ADD COLUMN `id1` int NOT NULL auto_increment FIRST,
  ADD COLUMN `id2` int NOT NULL AFTER `id1`,
  ADD PRIMARY KEY (`id1`, `id2`);

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
