
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;

ALTER TABLE `t`
  CHANGE COLUMN `c2` `c2` int(11) NOT NULL FIRST,
  CHANGE COLUMN `c3` `c3` int(11) NOT NULL AFTER `c2`;

SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
