name: CI
on:
  push:
    branches:
      - '*'
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
        mysql-version:
          - "5.6"
          - "5.7"
          - "8.0"
        dependencies:
          - lowest
          - highest
    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        ports:
          - 3306/tcp
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
          -e MYSQL_ALLOW_EMPTY_PASSWORD=1
          -e MYSQL_DATABASE=test
          -e MYSQL_USER=test
          -e MYSQL_PASSWORD=pass
          --entrypoint sh
          mysql:${{ matrix.mysql-version }}
          -c "exec docker-entrypoint.sh mysqld --default-authentication-plugin=mysql_native_password"
    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: pdo_mysql

      - uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ matrix.php-version }}-${{ matrix.dependencies }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php-version }}-
            ${{ runner.os }}-php-

      - uses: ramsey/composer-install@v1
        with:
          dependency-versions: ${{ matrix.dependencies }}

      - run: vendor/bin/phpunit.phar --colors --coverage-text
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          MYSQL_USER: test
          MYSQL_PASSWORD: pass
          MYSQL_DATABASE: test
          XDEBUG_MODE: coverage

  cs:
    runs-on: ubuntu-latest
    container:
      image: ngyuki/php-dev:7.4
    steps:
      - uses: actions/checkout@v2
      - run: php-cs-fixer fix --diff --dry-run --ansi -v
